#!/bin/bash

#SBATCH --job-name=register_distribution
#SBATCH --account=project_462000353
#SBATCH --partition=small
#SBATCH --time=12:00:00
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --mem=128G
#SBATCH --output=slurm-logs/array_%A_%a.out
#SBATCH --error=slurm-logs/array_%A_%a.err
#SBATCH --array=0-3

# If run without sbatch, invoke here
if [ -z "$SLURM_JOB_ID" ]; then
    sbatch "$0" "$@"
    exit
fi

# See http://redsymbol.net/articles/unofficial-bash-strict-mode/
set -euo pipefail

rm -f "slurm-logs/current_${SLURM_JOB_NAME}_${SLURM_ARRAY_TASK_ID}.err"
rm -f "slurm-logs/current_${SLURM_JOB_NAME}_${SLURM_ARRAY_TASK_ID}.out"
ln -s "array_${SLURM_ARRAY_JOB_ID}_${SLURM_ARRAY_TASK_ID}.err" "slurm-logs/current_${SLURM_JOB_NAME}_${SLURM_ARRAY_TASK_ID}.err"
ln -s "array_${SLURM_ARRAY_JOB_ID}_${SLURM_ARRAY_TASK_ID}.out" "slurm-logs/current_${SLURM_JOB_NAME}_${SLURM_ARRAY_TASK_ID}.out"

read -r FILE < <(sed -n "$((SLURM_ARRAY_TASK_ID + 1))p" files.txt)

SOURCE_DIR="/scratch/project_462000353/tlundber/umap-embeddings/data/model_embeds/cleaned/bge-m3-fold-6/th-optimised"
DEST_DIR="/scratch/project_462000353/tlundber/umap-embeddings/register-distribution-results-th-optimised"

module purge
module use /appl/local/csc/modulefiles
module load pytorch

python3 register_dist.py "${SOURCE_DIR}/${FILE}" "$DEST_DIR"

# Check if transfer was successful
if [ $? -eq 0 ]; then
	echo "Job ${SLURM_ARRAY_JOB_ID}_${SLURM_ARRAY_TASK_ID} completed successfully."
else
	echo "Job ${SLURM_ARRAY_JOB_ID}_${SLURM_ARRAY_TASK_ID} failed."
fi

sacct -o jobid,elapsed -j "${SLURM_ARRAY_JOB_ID}_${SLURM_ARRAY_TASK_ID}"
